### ISSUE TITLE
Create UI For The App

### ISSUE THREAD

**Issue by joykangangi** [hngx-org/ai-story-completer#1]
These are the major screens in the application. 

### TO-DOs
- [x] Create Splash Screen
- [x] Create Stories List Screen
- [x] Create Story Screen
- [x] Create Bottom Sheet Layout
- [x] Create Detail Screen
- [x] Handle the state changes and updates for each of the Screens
