### ISSUE TITLE
Local Database

### ISSUE THREAD

**Issue by joykangangi** [hngx-org/ai-story-completer#2]
Handle the local storage using `Room Database`

### TO-DOs
- [x] Implement entity class
- [x] Implement the `DAO` interface with the necessary CRUD methods.
- [x] Implement the `Database class`
- [x] Implement the repository to be used in UI.
- [x] Create functions in the viewmodel which will be called to update the database.
