### ISSUE TITLE
App Review Actions

### ISSUE THREAD

**Issue by joykangangi** [hngx-org/ai-story-completer#27]
This is the feedback on improvements from the app review.

### TO-DOs
- [ ] Display Progress Bar for Login and Sign up Screens
- [ ] Remove the `SnackBar` in the `StoriesList Screen`.
- [ ] Correct state management for the generated text and user input.
- [ ] Ensure the generated text does not stop in the middle of a sentence.
- [ ] Display animation while waiting for generated text.
- [ ] Redesign the `Profile Page`
### EXTRAs
- [ ] Add navigation animations 
- [ ] Make font uniform in the app.
