### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by joykangangi** [hngx-org/ai-story-completer#3]
This involves how users can navigate within the application.

### TO-DOs
- [x] Implement the navigation graph.
- [x] Add the navigation routes.
- [x] Ensure the navigation buttons on each screen are functional.
- [x] Add smooth animations between screens.
- [x] Pass correct navigation arguments to a screen when necessary.
