### ISSUE TITLE
OpenAI Integration

### ISSUE THREAD

**Issue by joykangangi** [hngx-org/ai-story-completer#5]
This involves calling the API from the `OpenAI` library. 

### TO-DOs
- [x] Implement the library in the `Create Story` Viewmodel.
- [x] Test the functionality of the library.
- [x] Prompt engineer the model with the required parameters.
